### ISSUE TITLE
default_paths.yaml is not pushed to conda-forge

### ISSUE THREAD

**Issue by chrisjwin** [FZJ-IEK3-VSA/RESKit#32]
The file default_paths.yaml is not being pushed to conda-forge, rendering the conda-forge version unusable. Maybe there is a filetype constraint or so, in that case adapt structure. Are you aware of any such constraints @julian-belina ? FYI @phil-fzj @d-franzmann

**Comment by julian-belina** [comment]
This needs to be configured in pyproject.toml https://stackoverflow.com/questions/69647590/specifying-package-data-in-pyproject-toml

**Comment by julian-belina** [comment]
This has been fixed in 0.4.2

**Comment by phil-fzj** [comment]
File is still not included. Create test to investigate this behavior.

**Comment by julian-belina** [comment]
Has been fixed in 0.4.2
